"""initial

Revision ID: 1552dde1c821
Revises: 
Create Date: 2026-03-22 03:10:02.050659
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1552dde1c821'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('total_pnl_usdt', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_fees_usdt', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('circuit_broken', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='tradeside'), nullable=False),
    sa.Column('strategy', sa.Enum('grid_bot', 'funding_arb', 'pair_trade', name='strategyname'), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', name='ordertype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee_usdt', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('pnl_usdt', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('filled', 'partial', 'failed', name='tradestatus'), nullable=False),
    sa.Column('binance_order_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
